<a href="https://colab.research.google.com/github/addy1997/Task9-personality-prediction/blob/main/Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [73]:
from keras.models import load_model
new_model1 = load_model('/content/Agreeaableness.model')
new_model2 = load_model('/content/Openness.model')
new_model3 = load_model('/content/Extraversion.model')
new_model4 = load_model('/content/Conscientiousness.model')
new_model5 = load_model('/content/Neuroticism.model')

In [74]:
from keras.optimizers import RMSprop
opt = RMSprop(lr=0.001, rho=0.9, epsilon=None)

new_model1.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model2.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model3.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model4.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])
new_model5.compile(loss='mean_squared_error', 
              optimizer=opt,
              metrics=['accuracy'])

In [86]:
import pickle
import numpy as np

def get_idx_from_sent(sent, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentence into a list of indices. Pad with zeroes.
    """
    x = []
    pad = kernel_size - 1
    for i in range(pad):
        x.append(0)
    words = sent.split()
    for word in words:
        if word in word_idx_map:
            x.append(word_idx_map[word])
    while len(x) < max_l+2*pad:
        x.append(0)
    return x

def make_idx_data(revs, word_idx_map, max_l=51, kernel_size=5):
    """
    Transforms sentences into a 2-d matrix.
    """
    test = []
    for rev in revs:
        sent = get_idx_from_sent(rev['text'], word_idx_map, max_l, kernel_size)
        sent.append(rev['y'])
        test.append(sent)
    test = np.array(test, dtype=np.int)
    return test


print ("loading data...")
with open("test_c.pickle", 'rb') as f:
    x = pickle.load(f, encoding='latin')
revs, W, word_idx_map, vocab = x[0], x[1], x[2], x[3]
print ("data loaded!")


datasets = make_idx_data(revs, word_idx_map,max_l = 2721,kernel_size=5)
print(datasets)

loading data...
data loaded!
[[0 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 3]
 ...
 [0 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 3]
 [0 0 0 ... 0 0 3]]


In [87]:
Nt = datasets.shape[0]
test_X = np.zeros((Nt,2729), dtype=np.int)
for i in range(Nt):
    for j in range(2729):
       test_X[i, j] = datasets[i, j]
    
print ('test_X.shape = {}'.format(test_X.shape))

test_X.shape = (9917, 2729)


In [88]:
test_X[0][298]

0

In [89]:
o = new_model1.predict(test_X, verbose = 1)

310/310 [==============================] - 7s 23ms/step


In [90]:
c = new_model2.predict(test_X, verbose = 1)

310/310 [==============================] - 7s 24ms/step


In [96]:
e = new_model3.predict(test_X, verbose = 1)

310/310 [==============================] - 7s 23ms/step


In [92]:
a = new_model4.predict(test_X, verbose = 1)

310/310 [==============================] - 7s 24ms/step


In [93]:
n = new_model5.predict(test_X, verbose = 1)

310/310 [==============================] - 7s 24ms/step
